### ISSUE TITLE
Getting Connection Error

### ISSUE THREAD

**Issue by rockscripts** [neoctobers/TeleInviter#3]
Thank you for this great project. i installed modules required and configured api id, hash and follow session settings but i'm having error messages. Can you help me please. 
**SESSION**
```
# Sessions
sessions = {
    'session_name':
        {
            'name': 'rockscripts',
            'area_code': '+34',
            'phone': '+34643124304',
            'proxy': (socks.SOCKS5, 'localhost', 1080),
        },
}
```
**ERROR MESSAGES**

```
rockscripts@rockscripts:~/Documents/TeleInviter$ ./start.py

Launching client "rockscripts" ...Traceback (most recent call last):
  File "./start.py", line 23, in <module>
    clients[key] = TeleInviter(client_session, db=TeleDb)
  File "/home/rockscripts/Documents/TeleInviter/TeleInviter.py", line 32, in __init__
    self._client = self._init_client(client_session)
  File "/home/rockscripts/Documents/TeleInviter/TeleInviter.py", line 81, in _init_client
    client.connect()
  File "/home/rockscripts/.local/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py", line 288, in connect
    self.session.server_address, self.session.port)
  File "/home/rockscripts/.local/lib/python3.6/site-packages/telethon/network/mtprotosender.py", line 128, in connect
    self._connect()
  File "/home/rockscripts/.local/lib/python3.6/site-packages/telethon/network/mtprotosender.py", line 253, in _connect
    .format(self._retries))
ConnectionError: Connection to Telegram failed 5 times
```

**Comment by rockscripts** [comment]
i tested with servers IPs displayed in App configuration https://my.telegram.org/apps in telethon/client/telegrambaseclient.py but not effects
![screenshot from 2018-07-31 15-50-26](https://user-images.githubusercontent.com/20305057/43471095-e8271df4-94c8-11e8-82a3-46eb7f876d68.png)

**Comment by neoctobers** [comment]
that seems a network error.

if u don't need a socks5 proxy, just set the `proxy` as `None` in `conf.sessions`.

**Comment by neoctobers** [comment]
if u are in the GFW

u may run a shadowsocks or sth., and ur `localhost` will be a socks5 proxy server.

u can check the setting of proxy, ip and port...

**Comment by neoctobers** [comment]
Check the proxy settings, bro. and i will close this issue.
